# This is the utilities configuration file.
# Please make your changes here.
#
# To call variables in a utility script:
# from cosipy.utilities.config import UtilitiesConfig
# in_K = UtilitiesConfig.aws2cosipy.names["in_K"]
#
# Alternatively:
# cfg_names = UtilitiesConfig.aws2cosipy.names
# in_K = cfg_names["in_K"]

# AWS2COSIPY
[aws2cosipy.names]
PRES_var = 'PRES'
T2_var = 'T2'
in_K = true  # input data is already in K
RH2_var = 'RH2'
G_var = 'G'
RRR_var = 'RRR'
U2_var = 'U2'
LWin_var = 'LWin'
SNOWFALL_var = 'SNOWFALL'
N_var = 'N'

[aws2cosipy.coords]
WRF = false
aggregate = false
aggregation_step = 'H'
delimiter = ','

[aws2cosipy.radiation]
radiationModule = 'Horayzon2022' # 'Moelg2009', 'Wohlfahrt2016', 'Horayzon2022', 'none'
LUT = false  # If there is already a Look-up-table for topographic shading and sky-view-factor built for this area, set to True
LUT_path = "./data/static/LUT_Rad.nc"
dtstep = 10800  # time step (s)
tcart = 4.24  # Station time correction in hour angle units (1 is 4 min)
timezone_lon = 15.0  # Longitude of station
zeni_thld = 89.0  # If you do not know the exact value for your location, set value to 89.0
ELEV_model = true
delimiter = ','

[aws2cosipy.points]
point_model = false #false
plon = 90.64
plat = 30.47
hgt = 5665.0

[aws2cosipy.station]
stationName = 'HEF'
stationAlt = 3030.0283
stationLat = 46.797478  # Latitude of station

[aws2cosipy.lapse]
lapse_T = -0.0065  # Temp K per  m
lapse_RH = 0.000  # RH % per m (0 to 1)
lapse_RRR = 0.0000  # mm per m
lapse_SNOWFALL = 0.0000  # Snowfall % per m (0 to 1)

# CREATE STATIC FILE
[create_static.paths]
static_folder = "./data/static/"
dem_path = "HEF/DEM/COPDEM30_HEF_Box.tif"
shape_path = "HEF/Shapefiles/HEF_RGI6.shp"
output_file = "HEF/HEF_static_300m_new.nc"
output_file_crop = "HEF/HEF_static_30m_crop_new.nc"

[create_static.coords]
tile = true
aggregate = true
aggregate_degree = 0.00277778
longitude_upper_left = 10.6
latitude_upper_left = 46.9
longitude_lower_right = 10.9
latitude_lower_right = 46.7
automatic_domain = true
crop_file = true
dist_search = 22.0 ## buffer size or lat lon corners influence how aggregated glacier is represented (changes no. GGPs)

# WRF2COSIPY
[wrf2cosipy.constants]
hu = 10  # Height of WRF wind velocity
lu_class = 24 # land use class for glaciers
